# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[migrations_directory]
dir = "/database/src/migration"

[print_schema]
custom_type_derives = ["diesel::query_builder::QueryId"]
file = "/database/src/schema.rs"
