version: "3"

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME}-master"
    image: "citusdata/citus:${TAG:-12.1.1}"
    labels: ["com.citusdata.role=Master"]
    environment: &AUTH
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGUSER: "${POSTGRES_USER}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    networks:
      datakoro_net:
        aliases:
          - datakoro_master

  worker:
    image: "citusdata/citus:${TAG:-12.1.1}"
    labels: ["com.citusdata.role=Worker"]
    depends_on: [manager]
    environment: *AUTH
    command: "/wait-for-manager.sh"
    volumes:
      - healthcheck_volume:/healthcheck
    networks:
      - datakoro_net

  manager:
    container_name: "${COMPOSE_PROJECT_NAME}-manager"
    image: "citusdata/membership-manager:0.3.0"
    volumes:
      - "${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock"
      - healthcheck_volume:/healthcheck
    depends_on: [master]
    environment: *AUTH
    networks:
      datakoro_net:
        aliases:
          - datakoro_manager

  datakoro_server:
    container_name: "${COMPOSE_PROJECT_NAME}-server"
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: tail -f /dev/null
    volumes:
      - .:/srv/datakoro
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@datakoro_master/${POSTGRES_USER}
      - RUN_SERVER=${RUN_SERVER}
    depends_on:
      - master
    networks:
      datakoro_net:
        aliases:
          - datakoro_server

  datakoro_server_nginx_development:
    image: "nginx:stable-bookworm"
    container_name: "${COMPOSE_PROJECT_NAME}-server-nginx-development"
    ports:
      - "${WEB_SERVER_PORT}:443"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    depends_on:
      - datakoro_server
    networks:
      datakoro_net:
        aliases:
          - datakoro_server_nginx_development
    profiles:
      - development

  datakoro_server_nginx_production:
    image: "nginx:stable-bookworm"
    container_name: "${COMPOSE_PROJECT_NAME}-server-nginx-production"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - /srv/certbot/etc/letsencrypt:/etc/letsencrypt
      - /srv/certbot/var/www/certbot:/var/www/certbot
    depends_on:
      - datakoro_server
    networks:
      datakoro_net:
        aliases:
          - datakoro_server_nginx_development
    profiles:
      - production

  certbot:
    image: certbot/certbot
    container_name: "${COMPOSE_PROJECT_NAME}-certbot"
    entrypoint: >
      /bin/sh -c '
      if [ ! -f /etc/letsencrypt/live/${CERTBOT_DOMAIN}/fullchain.pem ]; then
        certbot certonly --webroot -w /var/www/certbot -d ${CERTBOT_DOMAIN} --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email --non-interactive;
      fi;
      trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot;
        sleep 12h;
      done;
      '
    environment:
      - CERTBOT_EMAIL=${CERTBOT_EMAIL}
      - CERTBOT_DOMAIN=${CERTBOT_DOMAIN}
    volumes:
      - /srv/certbot/etc/letsencrypt:/etc/letsencrypt
      - /srv/certbot/var/www/certbot:/var/www/certbot
    networks:
      - datakoro_net
    depends_on:
      - datakoro_server_nginx_production
    deploy:
      placement:
        constraints:
          - node.role == manager
    profiles:
      - production
volumes:
  healthcheck_volume:
networks:
  datakoro_net:
